// Reactjs/mern/mern-app/src/Components/NavBar.jsx
import React from 'react'
import { Link } from 'react-router-dom'
export default function NavBar() {
  return (
    <div>
      <nav className='navbar navbar-dark bg-dark navbar-expand-sm'>
        <div className="container">
          <Link to={'/'} className='navbar-brand'>
            <i className="fa fa-mobile-phone" aria-hidden="true">
            </i>
            <span className='text-warning'>List Contacts</span>
          </Link>
          <Link to={'/contacts/add'} className='btn btn-warning text-dark'>
            <i className="fa fa-plus-circle" aria-hidden="true">
            </i>
            <span className='text-danger'>Add new Contact</span>
          </Link>
        </div>
      </nav>
    </div>
  )
}

// Angular18/RestApiExample/src/app/Components/nav-bar/nav-bar.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-nav-bar',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './nav-bar.component.html',
  styles: ``
})
export class NavBarComponent {
  title ="IMBD Application"
}

<div class="container">
    <div class="row">
        <h1 class="h1 text-center">{{title}}</h1>
        <div class="nav navbar navbar-expand-sm bg-danger">
            <div class="navbar-nav">
                <li class="navitem m-3">
                    <a class="nav-link btn btn-warning" routerLink="/">
                        <i class="fa fa-list" aria-hidden="true"></i>
                        Movie List
                    </a>
                </li>
                <li class="navitem m-3">
                    <a class="nav-link btn btn-warning" routerLink="/addMovie">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        Add new Movie
                    </a>
                </li>
                <li class="navitem m-3">
                    <a class="nav-link btn btn-warning" routerLink="/">
                        <i class="fa fa-amazon" aria-hidden="true"></i>
                        About Us
                    </a>
                </li>
            </div>
        </div>
    </div>
</div>
